function GetShortcuts() 
  return {
    "   <F3>             - Toggle File Sidebar (nerdtree)",
    "   <F4>             - Toggle Tag Bar",
    "   <F5>             - Toggle Undo History (gundo)",
    "   <F6>             - Toggle Syntastic",
    "   <F7>             - Toggle Spellcheck",
    "   <Leader> P       - Past highlighted in starting left space",
    "   <Leader> d       - Delete highlighted",
    "   <Leader> p       - Paste highlighted",
    "   <Leader> y       - Yank (cut) highlighted",
    "   <Leader> b       - Search throught open Buffers (previously files)",
    "   <Leader> f       - formate selected code",
    "   <Leader> l       - ...enable/disable color line at 80",
    "   <Leader> n       - Hide Search Highlight",
    "   <Leader> o       - Find files (fzf)",
    "   <Leader> q       - Quit Vim",
    "   <Leader> rn      - rename symbol",
    "   <Leader> s       - Show/Hide Whitespace",
    "   <Leader> w       - Save File",
    "   K                - show code documentation",
    "   Ctrl-b           - scroll full page up",
    "   Ctrl-c           - trigger code completion",
    "   Ctrl-d           - scroll down",
    "   Ctrl-f           - scroll full page down",
    "   Ctrl-u           - scroll up",
    "   gcc              - comment line or selected code",
    "   gd               - jump to code definition",
    "   gi               - jump to code implementation",
    "   gr               - jump to code references",
    "   gy               - jump to code type definition"
  }
end
