function GetShortcuts() 
  return {
    "<F3>             - Toggle File Sidebar (nerdtree)",
    "F4>             - Toggle Tag Bar",
    "F5>             - Toggle Undo History (gundo)",
    "F6>             - Toggle Syntastic",
    "F7>             - Toggle Spellcheck",
    "Leader>P        - Past highlighted in starting left space",
    "Leader>d        - Delete highlighted",
    "Leader>p        - Paste highlighted",
    "Leader>y        - Yank (cut) highlighted",
    "leader>b        - Search throught open Buffers (previously opened files)",
    "leader>f        - formate selected code",
    "leader>l        - ...enable/disable color line at 80",
    "leader>n        - Hide Search Highlight",
    "leader>o        - Find files (fzf)",
    "leader>q        - Quit Vim",
    "leader>rn       - rename symbol",
    "leader>s        - Show/Hide Whitespace",
    "leader>w        - Save File",
    "                - show code documentation",
    "trl-b           - scroll full page up",
    "trl-c           - trigger code completion",
    "trl-d           - scroll down",
    "trl-f           - scroll full page down",
    "trl-u           - scroll up",
    "cc              - comment line or selected code",
    "d               - jump to code definition",
    "i               - jump to code implementation",
    "r               - jump to code references",
    "y               - jump to code type definition"
  }
end
